In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib
import os

In [3]:
#data = pd.read_csv('18-19-season/[2018-10-16]-0021800001-PHI@BOS.csv')

## Create a list of all Lakers game files. (ie. files where the naem contains LAL) #

# Here, my path is : "C:/Users/mmiric/Documents/NBA Data/1718 NBA Data/TRAIN", but yours 
# might differ #

LAL_Files = []

for file in os.listdir("1718/TRAIN"):
    if "LAL" in file: 
        LAL_Files.append(file)

LAL_Files

['[2017-11-05]-0021700145-MEM@LAL.csv',
 '[2018-01-05]-0021700577-CHA@LAL.csv',
 '[2018-02-02]-0021700768-LAL@BKN.csv',
 '[2018-03-19]-0021701051-LAL@IND.csv',
 '[2017-12-25]-0021700497-MIN@LAL.csv',
 '[2018-04-11]-0021701228-LAL@LAC.csv',
 '[2018-02-10]-0021700830-LAL@DAL.csv',
 '[2018-04-10]-0021701218-HOU@LAL.csv',
 '[2017-12-29]-0021700529-LAC@LAL.csv',
 '[2017-10-19]-0021700016-LAC@LAL.csv',
 '[2017-12-03]-0021700338-HOU@LAL.csv',
 '[2017-10-27]-0021700076-TOR@LAL.csv',
 '[2018-02-06]-0021700804-PHX@LAL.csv',
 '[2017-12-23]-0021700491-POR@LAL.csv',
 '[2018-04-08]-0021701201-UTA@LAL.csv',
 '[2018-02-15]-0021700866-LAL@MIN.csv',
 '[2017-11-29]-0021700312-GSW@LAL.csv',
 '[2017-12-02]-0021700332-LAL@DEN.csv',
 '[2017-10-25]-0021700064-WAS@LAL.csv',
 '[2018-02-08]-0021700816-OKC@LAL.csv',
 '[2018-01-17]-0021700660-LAL@OKC.csv',
 '[2017-12-07]-0021700363-LAL@PHI.csv',
 '[2018-02-24]-0021700891-LAL@SAC.csv',
 '[2018-01-19]-0021700673-IND@LAL.csv',
 '[2017-11-09]-0021700164-LAL@WAS.csv',
 '[2017-12-27]-0021700515-MEM@LAL.csv',
 '[2017-11-22]-0021700266-LAL@SAC.csv',
 '[2018-01-07]-0021700590-ATL@LAL.csv',
 '[2018-01-09]-0021700602-SAC@LAL.csv',
 '[2017-12-09]-0021700377-LAL@CHA.csv',
 '[2018-03-16]-0021701034-MIA@LAL.csv',
 '[2018-03-26]-0021701104-LAL@DET.csv',
 '[2018-01-15]-0021700645-LAL@MEM.csv',
 '[2018-01-13]-0021700627-LAL@DAL.csv',
 '[2017-10-28]-0021700082-LAL@UTA.csv',
 '[2018-01-28]-0021700735-LAL@TOR.csv',
 '[2017-11-21]-0021700252-CHI@LAL.csv',
 '[2018-03-07]-0021700971-ORL@LAL.csv',
 '[2017-12-14]-0021700415-LAL@CLE.csv',
 '[2018-01-03]-0021700565-OKC@LAL.csv',
 '[2018-01-21]-0021700684-NYK@LAL.csv',
 '[2018-01-11]-0021700617-SAS@LAL.csv',
 '[2018-01-26]-0021700717-LAL@CHI.csv',
 '[2018-04-06]-0021701190-MIN@LAL.csv',
 '[2017-11-11]-0021700182-LAL@MIL.csv',
 '[2018-01-01]-0021700548-LAL@MIN.csv',
 '[2018-03-28]-0021701123-DAL@LAL.csv',
 '[2017-12-22]-0021700479-LAL@GSW.csv',
 '[2017-12-20]-0021700459-LAL@HOU.csv',
 '[2017-12-31]-0021700540-LAL@HOU.csv',
 '[2017-12-18]-0021700450-GSW@LAL.csv',
 '[2018-01-23]-0021700700-BOS@LAL.csv',
 '[2018-03-30]-0021701136-MIL@LAL.csv',
 '[2018-03-22]-0021701075-LAL@NOP.csv',
 '[2018-03-03]-0021700940-LAL@SAS.csv',
 '[2017-12-12]-0021700399-LAL@NYK.csv',
 '[2018-03-09]-0021700983-LAL@DEN.csv',
 '[2018-02-26]-0021700897-LAL@ATL.csv',
 '[2018-03-11]-0021701000-CLE@LAL.csv',
 '[2017-10-22]-0021700040-NOP@LAL.csv',
 '[2017-10-31]-0021700104-DET@LAL.csv',
 '[2018-03-24]-0021701092-LAL@MEM.csv',
 '[2018-03-05]-0021700956-POR@LAL.csv',
 '[2018-03-13]-0021701015-DEN@LAL.csv',
 '[2018-02-23]-0021700883-DAL@LAL.csv',
 '[2018-04-04]-0021701174-SAS@LAL.csv',
 '[2017-11-03]-0021700130-BKN@LAL.csv',
 '[2018-02-14]-0021700862-LAL@NOP.csv',
 '[2018-04-01]-0021701155-SAC@LAL.csv',
 '[2017-10-20]-0021700026-LAL@PHX.csv',
 '[2017-11-02]-0021700118-LAL@POR.csv',
 '[2017-11-17]-0021700227-PHX@LAL.csv',
 '[2017-11-19]-0021700240-DEN@LAL.csv',
 '[2017-11-13]-0021700196-LAL@PHX.csv',
 '[2017-11-08]-0021700161-LAL@BOS.csv']

In [4]:
LAL_Files[0:3]

['[2017-11-05]-0021700145-MEM@LAL.csv',
 '[2018-01-05]-0021700577-CHA@LAL.csv',
 '[2018-02-02]-0021700768-LAL@BKN.csv']

In [14]:
# Let's see the head (first 5 rows) in the first data file: 

Directory = "1718/TRAIN/"
# data = pd.read_csv(Directory + LAL_Files[0])

data=pd.read_csv(Directory + '[2017-10-17]-0021700001-BOS@CLE.csv')
data.head()

,game_id,data_set,date,a1,a2,a3,a4,a5,h1,h2,...,reason,result,steal,type,shot_distance,original_x,original_y,converted_x,converted_y,description
0,"=""0021700001""",2017-2018 Regular Season,2017-10-17,Gordon Hayward,Jayson Tatum,Al Horford,Jaylen Brown,Kyrie Irving,LeBron James,Jae Crowder,...,NaN,NaN,NaN,start of period,NaN,NaN,NaN,NaN,NaN,NaN
1,"=""0021700001""",2017-2018 Regular Season,2017-10-17,Gordon Hayward,Jayson Tatum,Al Horford,Jaylen Brown,Kyrie Irving,LeBron James,Jae Crowder,...,NaN,NaN,NaN,jump ball,NaN,NaN,NaN,NaN,NaN,Jump Ball Love vs. Horford: Tip to Irving
2,"=""0021700001""",2017-2018 Regular Season,2017-10-17,Gordon Hayward,Jayson Tatum,Al Horford,Jaylen Brown,Kyrie Irving,LeBron James,Jae Crowder,...,NaN,made,NaN,unknown,10.0,-1.0,100.0,25.1,15.0,Irving 10' Driving Floating Jump Shot (2 PTS) ...
3,"=""0021700001""",2017-2018 Regular Season,2017-10-17,Gordon Hayward,Jayson Tatum,Al Horford,Jaylen Brown,Kyrie Irving,LeBron James,Jae Crowder,...,NaN,missed,NaN,Layup,2.0,-18.0,4.0,23.2,88.6,"Horford BLOCK (1 BLK), MISS Rose 2' Layup"
4,"=""0021700001""",2017-2018 Regular Season,2017-10-17,Gordon Hayward,Jayson Tatum,Al Horford,Jaylen Brown,Kyrie Irving,LeBron James,Jae Crowder,...,NaN,NaN,NaN,rebound defensive,NaN,NaN,NaN,NaN,NaN,Horford REBOUND (Off:0 Def:1)

In [18]:
# Now, we have the lineups separate for the home and away team, but we dont have an indicator in the dataset
# for what is the home and away team. Therefore, we have to create separate datasets for 
# home / away teams. 

# Let's build the code for a single game, then we run for all games #. 

if "@LAL" in file: 
    HomeAway = "Home"
else: 
    HomeAway = "Away"

# CLEAN HOME DATA # 

if HomeAway == "Home":
    
    # Select only key columns # 
    
    temp_data = data[['h1', 'h2', 'h3', 'h4', 'h5','a1', 'a2', 'a3', 'a4', 'a5','player', 'team', 'points']]
    
    temp_data = temp_data.loc[temp_data['points'].notnull()]
    
    # Now, we are going to focus on a "player - position pair", and how many players scored / conceded points. 
    
    i = str(1)
    
    # Select only player and opponent #
    
    temp_data2 = temp_data[['h'+i, 'a'+i, 'player', 'team', 'points']]
    
    temp_data2.columns = ['LALPlayer', "OpponentPlayer", "Scorer", "Team", "Points"]
    
    # Construct Variables indicating whether a player has scored, or not.# 
    
    temp_data2['Team'] = np.where(temp_data2['Team'] == "LAL", 1, 0)
    
    temp_data2['Player'] = np.where(temp_data2['LALPlayer'] == temp_data2['Scorer'], 1, 0)
    
    temp_data2['OpposingPlayer'] = np.where(temp_data2['OpponentPlayer'] == temp_data2['Scorer'], 1, 0)

    temp_data2['ScoredMissed'] = np.where(temp_data2['Points'] == 0, "Missed", "Scored")
    
    temp_data2['Position'] = i
    
    # Calculate 
    
    temp_data2 = pd.pivot_table(temp_data2, index = ['LALPlayer', 'ScoredMissed'], values = ['Team','Player','OpposingPlayer'], aggfunc = np.sum)
    
    print(temp_data2.unstack())

                OpposingPlayer        Player          Team
ScoredMissed            Missed Scored Missed Scored Missed Scored
LALPlayer
Brandon Ingram               2      2      3      3     24     26
Brook Lopez                  0      2      0      0      3      7
Jordan Clarkson              0      0      1      0      2      1
Kyle Kuzma                   2      1      1      1     20     21
Lonzo Ball                   0      0      0      1      1      3

/Users/xiaojuezhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/xiaojuezhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/xiaojuezhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/xiaojuezhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/xiaojuezhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [34]:
data.loc[(data['h1']=='LeBron James')].iloc[-1,15] - data.loc[(data['h1']=='LeBron James')].iloc[0,15]

102

In [13]:
data.groupby('h1').count()

,game_id,data_set,date,a1,a2,a3,a4,a5,h2,h3,...,reason,result,steal,type,shot_distance,original_x,original_y,converted_x,converted_y,description
h1,,,,,,,,,,,,,,,,,,,,,
Brandon Ingram,201,201,201,201,201,201,201,201,201,201,...,26,93,4,201,81,81,81,81,81,197
Brook Lopez,29,29,29,29,29,29,29,29,29,29,...,4,16,1,29,14,14,14,14,14,29
Jordan Clarkson,14,14,14,14,14,14,14,14,14,14,...,4,5,1,14,4,4,4,4,4,14
Kentavious Caldwell-Pope,1,1,1,1,1,1,1,1,1,1,...,0,0,0,1,0,0,0,0,0,1
Kyle Kuzma,190,190,190,190,190,190,190,190,190,190,...,29,88,5,190,67,67,67,67,67,184
Lonzo Ball,12,12,12,12,12,12,12,12,12,12,...,0,7,0,12,6,6,6,6,6,11

In [53]:
k = ''
home_score_old, away_score_old = 0,0

for i,h1 in data['h1'].items():
    if h1 != k:
        print('on line: ', i , k, 'left')
        
        home_score_new = data.iloc[i]['home_score']
        away_score_new = data.iloc[i]['away_score']
        
        pm = (home_score_new - home_score_old) - (away_score_new - away_score_old)
        
        print('the old home_score when he joined is ', home_score_old)
        print('the old away_score when he joined is ', away_score_old)
        
        print('the new home_score when he left is ', home_score_new)
        print('the new away_score when he left is ', away_score_new)
    

        
        home_score_old = home_score_new
        away_score_old = away_score_new
        
        #print(pm)
        
    k = h1

on line:  0  left
the old home_score when he joined is  0
the old away_score when he joined is  0
the new home_score when he left is  0
the new away_score when he left is  0
on line:  86 LeBron James left
the old home_score when he joined is  0
the old away_score when he joined is  0
the new home_score when he left is  22
the new away_score when he left is  17
on line:  87 Jae Crowder left
the old home_score when he joined is  22
the old away_score when he joined is  17
the new home_score when he left is  22
the new away_score when he left is  17
on line:  116 Tristan Thompson left
the old home_score when he joined is  22
the old away_score when he joined is  17
the new home_score when he left is  29
the new away_score when he left is  19
on line:  200 Kevin Love left
the old home_score when he joined is  29
the old away_score when he joined is  19
the new home_score when he left is  48
the new away_score when he left is  30
on line:  320 LeBron James left
the old home_score when he joined is  48
the old away_score when he joined is  30
the new home_score when he left is  67
the new away_score when he left is  63
on line:  336 Jae Crowder left
the old home_score when he joined is  67
the old away_score when he joined is  63
the new home_score when he left is  69
the new away_score when he left is  63
on line:  365 Derrick Rose left
the old home_score when he joined is  69
the old away_score when he joined is  63
the new home_score when he left is  72
the new away_score when he left is  71