In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib
import os

In [3]:
#data = pd.read_csv('18-19-season/[2018-10-16]-0021800001-PHI@BOS.csv')

## Create a list of all Lakers game files. (ie. files where the naem contains LAL) #

# Here, my path is : "C:/Users/mmiric/Documents/NBA Data/1718 NBA Data/TRAIN", but yours 
# might differ #

LAL_Files = []

for file in os.listdir("1718/TRAIN"):
    if "LAL" in file: 
        LAL_Files.append(file)

LAL_Files

['[2017-11-05]-0021700145-MEM@LAL.csv',
 '[2018-01-05]-0021700577-CHA@LAL.csv',
 '[2018-02-02]-0021700768-LAL@BKN.csv',
 '[2018-03-19]-0021701051-LAL@IND.csv',
 '[2017-12-25]-0021700497-MIN@LAL.csv',
 '[2018-04-11]-0021701228-LAL@LAC.csv',
 '[2018-02-10]-0021700830-LAL@DAL.csv',
 '[2018-04-10]-0021701218-HOU@LAL.csv',
 '[2017-12-29]-0021700529-LAC@LAL.csv',
 '[2017-10-19]-0021700016-LAC@LAL.csv',
 '[2017-12-03]-0021700338-HOU@LAL.csv',
 '[2017-10-27]-0021700076-TOR@LAL.csv',
 '[2018-02-06]-0021700804-PHX@LAL.csv',
 '[2017-12-23]-0021700491-POR@LAL.csv',
 '[2018-04-08]-0021701201-UTA@LAL.csv',
 '[2018-02-15]-0021700866-LAL@MIN.csv',
 '[2017-11-29]-0021700312-GSW@LAL.csv',
 '[2017-12-02]-0021700332-LAL@DEN.csv',
 '[2017-10-25]-0021700064-WAS@LAL.csv',
 '[2018-02-08]-0021700816-OKC@LAL.csv',
 '[2018-01-17]-0021700660-LAL@OKC.csv',
 '[2017-12-07]-0021700363-LAL@PHI.csv',
 '[2018-02-24]-0021700891-LAL@SAC.csv',
 '[2018-01-19]-0021700673-IND@LAL.csv',
 '[2017-11-09]-0021700164-LAL@WAS.csv',
 '[2017-12-27]-0021700515-MEM@LAL.csv',
 '[2017-11-22]-0021700266-LAL@SAC.csv',
 '[2018-01-07]-0021700590-ATL@LAL.csv',
 '[2018-01-09]-0021700602-SAC@LAL.csv',
 '[2017-12-09]-0021700377-LAL@CHA.csv',
 '[2018-03-16]-0021701034-MIA@LAL.csv',
 '[2018-03-26]-0021701104-LAL@DET.csv',
 '[2018-01-15]-0021700645-LAL@MEM.csv',
 '[2018-01-13]-0021700627-LAL@DAL.csv',
 '[2017-10-28]-0021700082-LAL@UTA.csv',
 '[2018-01-28]-0021700735-LAL@TOR.csv',
 '[2017-11-21]-0021700252-CHI@LAL.csv',
 '[2018-03-07]-0021700971-ORL@LAL.csv',
 '[2017-12-14]-0021700415-LAL@CLE.csv',
 '[2018-01-03]-0021700565-OKC@LAL.csv',
 '[2018-01-21]-0021700684-NYK@LAL.csv',
 '[2018-01-11]-0021700617-SAS@LAL.csv',
 '[2018-01-26]-0021700717-LAL@CHI.csv',
 '[2018-04-06]-0021701190-MIN@LAL.csv',
 '[2017-11-11]-0021700182-LAL@MIL.csv',
 '[2018-01-01]-0021700548-LAL@MIN.csv',
 '[2018-03-28]-0021701123-DAL@LAL.csv',
 '[2017-12-22]-0021700479-LAL@GSW.csv',
 '[2017-12-20]-0021700459-LAL@HOU.csv',
 '[2017-12-31]-0021700540-LAL@HOU.csv',
 '[2017-12-18]-0021700450-GSW@LAL.csv',
 '[2018-01-23]-0021700700-BOS@LAL.csv',
 '[2018-03-30]-0021701136-MIL@LAL.csv',
 '[2018-03-22]-0021701075-LAL@NOP.csv',
 '[2018-03-03]-0021700940-LAL@SAS.csv',
 '[2017-12-12]-0021700399-LAL@NYK.csv',
 '[2018-03-09]-0021700983-LAL@DEN.csv',
 '[2018-02-26]-0021700897-LAL@ATL.csv',
 '[2018-03-11]-0021701000-CLE@LAL.csv',
 '[2017-10-22]-0021700040-NOP@LAL.csv',
 '[2017-10-31]-0021700104-DET@LAL.csv',
 '[2018-03-24]-0021701092-LAL@MEM.csv',
 '[2018-03-05]-0021700956-POR@LAL.csv',
 '[2018-03-13]-0021701015-DEN@LAL.csv',
 '[2018-02-23]-0021700883-DAL@LAL.csv',
 '[2018-04-04]-0021701174-SAS@LAL.csv',
 '[2017-11-03]-0021700130-BKN@LAL.csv',
 '[2018-02-14]-0021700862-LAL@NOP.csv',
 '[2018-04-01]-0021701155-SAC@LAL.csv',
 '[2017-10-20]-0021700026-LAL@PHX.csv',
 '[2017-11-02]-0021700118-LAL@POR.csv',
 '[2017-11-17]-0021700227-PHX@LAL.csv',
 '[2017-11-19]-0021700240-DEN@LAL.csv',
 '[2017-11-13]-0021700196-LAL@PHX.csv',
 '[2017-11-08]-0021700161-LAL@BOS.csv']

In [4]:
LAL_Files[0:3]

['[2017-11-05]-0021700145-MEM@LAL.csv',
 '[2018-01-05]-0021700577-CHA@LAL.csv',
 '[2018-02-02]-0021700768-LAL@BKN.csv']

In [14]:
# Let's see the head (first 5 rows) in the first data file: 

Directory = "1718/TRAIN/"
# data = pd.read_csv(Directory + LAL_Files[0])

data=pd.read_csv(Directory + '[2017-10-17]-0021700001-BOS@CLE.csv')
data.head()

,game_id,data_set,date,a1,a2,a3,a4,a5,h1,h2,...,reason,result,steal,type,shot_distance,original_x,original_y,converted_x,converted_y,description
0,"=""0021700001""",2017-2018 Regular Season,2017-10-17,Gordon Hayward,Jayson Tatum,Al Horford,Jaylen Brown,Kyrie Irving,LeBron James,Jae Crowder,...,NaN,NaN,NaN,start of period,NaN,NaN,NaN,NaN,NaN,NaN
1,"=""0021700001""",2017-2018 Regular Season,2017-10-17,Gordon Hayward,Jayson Tatum,Al Horford,Jaylen Brown,Kyrie Irving,LeBron James,Jae Crowder,...,NaN,NaN,NaN,jump ball,NaN,NaN,NaN,NaN,NaN,Jump Ball Love vs. Horford: Tip to Irving
2,"=""0021700001""",2017-2018 Regular Season,2017-10-17,Gordon Hayward,Jayson Tatum,Al Horford,Jaylen Brown,Kyrie Irving,LeBron James,Jae Crowder,...,NaN,made,NaN,unknown,10.0,-1.0,100.0,25.1,15.0,Irving 10' Driving Floating Jump Shot (2 PTS) ...
3,"=""0021700001""",2017-2018 Regular Season,2017-10-17,Gordon Hayward,Jayson Tatum,Al Horford,Jaylen Brown,Kyrie Irving,LeBron James,Jae Crowder,...,NaN,missed,NaN,Layup,2.0,-18.0,4.0,23.2,88.6,"Horford BLOCK (1 BLK), MISS Rose 2' Layup"
4,"=""0021700001""",2017-2018 Regular Season,2017-10-17,Gordon Hayward,Jayson Tatum,Al Horford,Jaylen Brown,Kyrie Irving,LeBron James,Jae Crowder,...,NaN,NaN,NaN,rebound defensive,NaN,NaN,NaN,NaN,NaN,Horford REBOUND (Off:0 Def:1)

In [18]:
# Now, we have the lineups separate for the home and away team, but we dont have an indicator in the dataset
# for what is the home and away team. Therefore, we have to create separate datasets for 
# home / away teams. 

# Let's build the code for a single game, then we run for all games #. 

if "@LAL" in file: 
    HomeAway = "Home"
else: 
    HomeAway = "Away"

# CLEAN HOME DATA # 

if HomeAway == "Home":
    
    # Select only key columns # 
    
    temp_data = data[['h1', 'h2', 'h3', 'h4', 'h5','a1', 'a2', 'a3', 'a4', 'a5','player', 'team', 'points']]
    
    temp_data = temp_data.loc[temp_data['points'].notnull()]
    
    # Now, we are going to focus on a "player - position pair", and how many players scored / conceded points. 
    
    i = str(1)
    
    # Select only player and opponent #
    
    temp_data2 = temp_data[['h'+i, 'a'+i, 'player', 'team', 'points']]
    
    temp_data2.columns = ['LALPlayer', "OpponentPlayer", "Scorer", "Team", "Points"]
    
    # Construct Variables indicating whether a player has scored, or not.# 
    
    temp_data2['Team'] = np.where(temp_data2['Team'] == "LAL", 1, 0)
    
    temp_data2['Player'] = np.where(temp_data2['LALPlayer'] == temp_data2['Scorer'], 1, 0)
    
    temp_data2['OpposingPlayer'] = np.where(temp_data2['OpponentPlayer'] == temp_data2['Scorer'], 1, 0)

    temp_data2['ScoredMissed'] = np.where(temp_data2['Points'] == 0, "Missed", "Scored")
    
    temp_data2['Position'] = i
    
    # Calculate 
    
    temp_data2 = pd.pivot_table(temp_data2, index = ['LALPlayer', 'ScoredMissed'], values = ['Team','Player','OpposingPlayer'], aggfunc = np.sum)
    
    print(temp_data2.unstack())

                OpposingPlayer        Player          Team
ScoredMissed            Missed Scored Missed Scored Missed Scored
LALPlayer
Brandon Ingram               2      2      3      3     24     26
Brook Lopez                  0      2      0      0      3      7
Jordan Clarkson              0      0      1      0      2      1
Kyle Kuzma                   2      1      1      1     20     21
Lonzo Ball                   0      0      0      1      1      3

/Users/xiaojuezhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/xiaojuezhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/xiaojuezhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/xiaojuezhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/xiaojuezhang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [34]:
data.loc[(data['h1']=='LeBron James')].iloc[-1,15] - data.loc[(data['h1']=='LeBron James')].iloc[0,15]

102

In [13]:
data.groupby('h1').count()

,game_id,data_set,date,a1,a2,a3,a4,a5,h2,h3,...,reason,result,steal,type,shot_distance,original_x,original_y,converted_x,converted_y,description
h1,,,,,,,,,,,,,,,,,,,,,
Brandon Ingram,201,201,201,201,201,201,201,201,201,201,...,26,93,4,201,81,81,81,81,81,197
Brook Lopez,29,29,29,29,29,29,29,29,29,29,...,4,16,1,29,14,14,14,14,14,29
Jordan Clarkson,14,14,14,14,14,14,14,14,14,14,...,4,5,1,14,4,4,4,4,4,14
Kentavious Caldwell-Pope,1,1,1,1,1,1,1,1,1,1,...,0,0,0,1,0,0,0,0,0,1
Kyle Kuzma,190,190,190,190,190,190,190,190,190,190,...,29,88,5,190,67,67,67,67,67,184
Lonzo Ball,12,12,12,12,12,12,12,12,12,12,...,0,7,0,12,6,6,6,6,6,11

In [53]:
k = ''
home_score_old, away_score_old = 0,0

for i,h1 in data['h1'].items():
    if h1 != k:
        print('on line: ', i , k, 'left')
        
        home_score_new = data.iloc[i]['home_score']
        away_score_new = data.iloc[i]['away_score']
        
        pm = (home_score_new - home_score_old) - (away_score_new - away_score_old)
        
        print('the old home_score when he joined is ', home_score_old)
        print('the old away_score when he joined is ', away_score_old)
        
        print('the new home_score when he left is ', home_score_new)
        print('the new away_score when he left is ', away_score_new)
    

        
        home_score_old = home_score_new
        away_score_old = away_score_new
        
        #print(pm)
        
    k = h1

on line:  0  left
the old home_score when he joined is  0
the old away_score when he joined is  0
the new home_score when he left is  0
the new away_score when he left is  0
on line:  86 LeBron James left
the old home_score when he joined is  0
the old away_score when he joined is  0
the new home_score when he left is  22
the new away_score when he left is  17
on line:  87 Jae Crowder left
the old home_score when he joined is  22
the old away_score when he joined is  17
the new home_score when he left is  22
the new away_score when he left is  17
on line:  116 Tristan Thompson left
the old home_score when he joined is  22
the old away_score when he joined is  17
the new home_score when he left is  29
the new away_score when he left is  19
on line:  200 Kevin Love left
the old home_score when he joined is  29
the old away_score when he joined is  19
the new home_score when he left is  48
the new away_score when he left is  30
on line:  320 LeBron James left
the old home_score when he joined is  48
the old away_score when he joined is  30
the new home_score when he left is  67
the new away_score when he left is  63
on line:  336 Jae Crowder left
the old home_score when he joined is  67
the old away_score when he joined is  63
the new home_score when he left is  69
the new away_score when he left is  63
on line:  365 Derrick Rose left
the old home_score when he joined is  69
the old away_score when he joined is  63
the new home_score when he left is  72
the new away_score when he left is  71

In [64]:
home_score_old, away_score_old = 0,0

for i, d in data.iteritems():
    if d['home_score'] == home_score_new

0      ="0021700001"
1      ="0021700001"
2      ="0021700001"
3      ="0021700001"
4      ="0021700001"
5      ="0021700001"
6      ="0021700001"
7      ="0021700001"
8      ="0021700001"
9      ="0021700001"
10     ="0021700001"
11     ="0021700001"
12     ="0021700001"
13     ="0021700001"
14     ="0021700001"
15     ="0021700001"
16     ="0021700001"
17     ="0021700001"
18     ="0021700001"
19     ="0021700001"
20     ="0021700001"
21     ="0021700001"
22     ="0021700001"
23     ="0021700001"
24     ="0021700001"
25     ="0021700001"
26     ="0021700001"
27     ="0021700001"
28     ="0021700001"
29     ="0021700001"
           ...
447    ="0021700001"
448    ="0021700001"
449    ="0021700001"
450    ="0021700001"
451    ="0021700001"
452    ="0021700001"
453    ="0021700001"
454    ="0021700001"
455    ="0021700001"
456    ="0021700001"
457    ="0021700001"
458    ="0021700001"
459    ="0021700001"
460    ="0021700001"
461    ="0021700001"
462    ="0021700001"
463    ="0021700001"
464    ="0021700001"
465    ="0021700001"
466    ="0021700001"
467    ="0021700001"
468    ="0021700001"
469    ="0021700001"
470    ="0021700001"
471    ="0021700001"
472    ="0021700001"
473    ="0021700001"
474    ="0021700001"
475    ="0021700001"
476    ="0021700001"
Name: game_id, Length: 477, dtype: object
0      2017-2018 Regular Season
1      2017-2018 Regular Season
2      2017-2018 Regular Season
3      2017-2018 Regular Season
4      2017-2018 Regular Season
5      2017-2018 Regular Season
6      2017-2018 Regular Season
7      2017-2018 Regular Season
8      2017-2018 Regular Season
9      2017-2018 Regular Season
10     2017-2018 Regular Season
11     2017-2018 Regular Season
12     2017-2018 Regular Season
13     2017-2018 Regular Season
14     2017-2018 Regular Season
15     2017-2018 Regular Season
16     2017-2018 Regular Season
17     2017-2018 Regular Season
18     2017-2018 Regular Season
19     2017-2018 Regular Season
20     2017-2018 Regular Season
21     2017-2018 Regular Season
22     2017-2018 Regular Season
23     2017-2018 Regular Season
24     2017-2018 Regular Season
25     2017-2018 Regular Season
26     2017-2018 Regular Season
27     2017-2018 Regular Season
28     2017-2018 Regular Season
29     2017-2018 Regular Season
                 ...
447    2017-2018 Regular Season
448    2017-2018 Regular Season
449    2017-2018 Regular Season
450    2017-2018 Regular Season
451    2017-2018 Regular Season
452    2017-2018 Regular Season
453    2017-2018 Regular Season
454    2017-2018 Regular Season
455    2017-2018 Regular Season
456    2017-2018 Regular Season
457    2017-2018 Regular Season
458    2017-2018 Regular Season
459    2017-2018 Regular Season
460    2017-2018 Regular Season
461    2017-2018 Regular Season
462    2017-2018 Regular Season
463    2017-2018 Regular Season
464    2017-2018 Regular Season
465    2017-2018 Regular Season
466    2017-2018 Regular Season
467    2017-2018 Regular Season
468    2017-2018 Regular Season
469    2017-2018 Regular Season
470    2017-2018 Regular Season
471    2017-2018 Regular Season
472    2017-2018 Regular Season
473    2017-2018 Regular Season
474    2017-2018 Regular Season
475    2017-2018 Regular Season
476    2017-2018 Regular Season
Name: data_set, Length: 477, dtype: object
0      2017-10-17
1      2017-10-17
2      2017-10-17
3      2017-10-17
4      2017-10-17
5      2017-10-17
6      2017-10-17
7      2017-10-17
8      2017-10-17
9      2017-10-17
10     2017-10-17
11     2017-10-17
12     2017-10-17
13     2017-10-17
14     2017-10-17
15     2017-10-17
16     2017-10-17
17     2017-10-17
18     2017-10-17
19     2017-10-17
20     2017-10-17
21     2017-10-17
22     2017-10-17
23     2017-10-17
24     2017-10-17
25     2017-10-17
26     2017-10-17
27     2017-10-17
28     2017-10-17
29     2017-10-17
          ...
447    2017-10-17
448    2017-10-17
449    2017-10-17
450    2017-10-17
451    2017-10-17
452    2017-10-17
453    2017-10-17
454    2017-10-17
455    2017-10-17
456    2017-10-17
457    2017-10-17
458    2017-10-17
459    2017-10-17
460    2017-10-17
461    2017-10-17
462    2017-10-17
463    2017-10-17
464    2017-10-17
465    2017-10-17
466    2017-10-17
467    2017-10-17
468    2017-10-17
469    2017-10-17
470    2017-10-17
471    2017-10-17
472    2017-10-17
473    2017-10-17
474    2017-10-17
475    2017-10-17
476    2017-10-17
Name: date, Length: 477, dtype: object
0      Gordon Hayward
1      Gordon Hayward
2      Gordon Hayward
3      Gordon Hayward
4      Gordon Hayward
5      Gordon Hayward
6      Gordon Hayward
7      Gordon Hayward
8      Gordon Hayward
9      Gordon Hayward
10     Gordon Hayward
11     Gordon Hayward
12     Gordon Hayward
13     Gordon Hayward
14     Gordon Hayward
15     Gordon Hayward
16     Gordon Hayward
17     Gordon Hayward
18     Gordon Hayward
19     Gordon Hayward
20     Gordon Hayward
21     Gordon Hayward
22     Gordon Hayward
23     Gordon Hayward
24     Gordon Hayward
25     Gordon Hayward
26     Gordon Hayward
27     Gordon Hayward
28     Gordon Hayward
29     Gordon Hayward
            ...
447      Jaylen Brown
448      Jaylen Brown
449      Jaylen Brown
450      Jaylen Brown
451      Jaylen Brown
452      Jaylen Brown
453      Jaylen Brown
454      Jaylen Brown
455      Jaylen Brown
456      Jaylen Brown
457      Jaylen Brown
458      Jaylen Brown
459      Jaylen Brown
460      Jaylen Brown
461      Jaylen Brown
462      Jaylen Brown
463      Jaylen Brown
464      Jaylen Brown
465      Jaylen Brown
466      Jaylen Brown
467      Jaylen Brown
468      Jaylen Brown
469      Jaylen Brown
470      Jaylen Brown
471      Jaylen Brown
472      Jaylen Brown
473      Jaylen Brown
474      Jaylen Brown
475      Jaylen Brown
476      Jaylen Brown
Name: a1, Length: 477, dtype: object
0      Jayson Tatum
1      Jayson Tatum
2      Jayson Tatum
3      Jayson Tatum
4      Jayson Tatum
5      Jayson Tatum
6      Jayson Tatum
7      Jayson Tatum
8      Jayson Tatum
9      Jayson Tatum
10     Jayson Tatum
11     Jayson Tatum
12     Jayson Tatum
13     Jayson Tatum
14     Jayson Tatum
15     Jayson Tatum
16     Jayson Tatum
17     Jayson Tatum
18     Jayson Tatum
19     Jayson Tatum
20     Jayson Tatum
21     Jayson Tatum
22     Jayson Tatum
23     Jayson Tatum
24     Jayson Tatum
25     Jayson Tatum
26     Jayson Tatum
27     Jayson Tatum
28     Jayson Tatum
29     Jayson Tatum
           ...
447    Kyrie Irving
448    Kyrie Irving
449    Kyrie Irving
450    Kyrie Irving
451    Kyrie Irving
452    Kyrie Irving
453    Kyrie Irving
454    Kyrie Irving
455    Kyrie Irving
456    Kyrie Irving
457    Kyrie Irving
458    Kyrie Irving
459    Kyrie Irving
460    Kyrie Irving
461    Kyrie Irving
462    Kyrie Irving
463    Kyrie Irving
464    Kyrie Irving
465    Kyrie Irving
466    Kyrie Irving
467    Kyrie Irving
468    Kyrie Irving
469    Kyrie Irving
470    Kyrie Irving
471    Kyrie Irving
472    Kyrie Irving
473    Kyrie Irving
474    Kyrie Irving
475    Kyrie Irving
476    Kyrie Irving
Name: a2, Length: 477, dtype: object
0        Al Horford
1        Al Horford
2        Al Horford
3        Al Horford
4        Al Horford
5        Al Horford
6        Al Horford
7        Al Horford
8        Al Horford
9        Al Horford
10       Al Horford
11       Al Horford
12       Al Horford
13       Al Horford
14       Al Horford
15       Al Horford
16       Al Horford
17       Al Horford
18       Al Horford
19       Al Horford
20       Al Horford
21       Al Horford
22       Al Horford
23       Al Horford
24       Al Horford
25       Al Horford
26       Al Horford
27       Al Horford
28       Al Horford
29       Al Horford
           ...
447    Jayson Tatum
448    Jayson Tatum
449    Jayson Tatum
450    Jayson Tatum
451    Jayson Tatum
452    Jayson Tatum
453    Jayson Tatum
454    Jayson Tatum
455    Jayson Tatum
456    Jayson Tatum
457    Jayson Tatum
458    Jayson Tatum
459    Jayson Tatum
460    Jayson Tatum
461    Jayson Tatum
462    Jayson Tatum
463    Jayson Tatum
464    Jayson Tatum
465    Jayson Tatum
466    Jayson Tatum
467    Jayson Tatum
468    Jayson Tatum
469    Jayson Tatum
470    Jayson Tatum
471    Jayson Tatum
472    Jayson Tatum
473    Jayson Tatum
474    Jayson Tatum
475    Jayson Tatum
476    Jayson Tatum
Name: a3, Length: 477, dtype: object
0      Jaylen Brown
1      Jaylen Brown
2      Jaylen Brown
3      Jaylen Brown
4      Jaylen Brown
5      Jaylen Brown
6      Jaylen Brown
7      Jaylen Brown
8      Jaylen Brown
9      Jaylen Brown
10     Jaylen Brown
11     Jaylen Brown
12     Jaylen Brown
13     Jaylen Brown
14     Jaylen Brown
15     Jaylen Brown
16     Jaylen Brown
17     Jaylen Brown
18     Jaylen Brown
19     Jaylen Brown
20     Jaylen Brown
21     Jaylen Brown
22     Jaylen Brown
23     Jaylen Brown
24     Jaylen Brown
25     Jaylen Brown
26     Jaylen Brown
27     Jaylen Brown
28     Jaylen Brown
29     Jaylen Brown
           ...
447      Al Horford
448      Al Horford
449      Al Horford
450      Al Horford
451      Al Horford
452      Al Horford
453      Al Horford
454      Al Horford
455      Al Horford
456      Al Horford
457      Al Horford
458      Al Horford
459      Al Horford
460      Al Horford
461      Al Horford
462      Al Horford
463      Al Horford
464      Al Horford
465      Al Horford
466      Al Horford
467      Al Horford
468      Al Horford
469      Al Horford
470      Al Horford
471      Al Horford
472      Al Horford
473      Al Horford
474      Al Horford
475      Al Horford
476      Al Horford
Name: a4, Length: 477, dtype: object
0      Kyrie Irving
1      Kyrie Irving
2      Kyrie Irving
3      Kyrie Irving
4      Kyrie Irving
5      Kyrie Irving
6      Kyrie Irving
7      Kyrie Irving
8      Kyrie Irving
9      Kyrie Irving
10     Kyrie Irving
11     Kyrie Irving
12     Kyrie Irving
13     Kyrie Irving
14     Kyrie Irving
15     Kyrie Irving
16     Kyrie Irving
17     Kyrie Irving
18     Kyrie Irving
19     Kyrie Irving
20     Kyrie Irving
21     Kyrie Irving
22     Kyrie Irving
23     Kyrie Irving
24     Kyrie Irving
25     Kyrie Irving
26     Kyrie Irving
27     Kyrie Irving
28     Kyrie Irving
29     Kyrie Irving
           ...
447    Marcus Smart
448    Marcus Smart
449    Marcus Smart
450    Marcus Smart
451    Marcus Smart
452    Marcus Smart
453    Marcus Smart
454    Marcus Smart
455    Marcus Smart
456    Marcus Smart
457    Marcus Smart
458    Marcus Smart
459    Marcus Smart
460    Marcus Smart
461    Marcus Smart
462    Marcus Smart
463    Marcus Smart
464    Marcus Smart
465    Marcus Smart
466    Marcus Smart
467    Marcus Smart
468    Marcus Smart
469    Marcus Smart
470    Marcus Smart
471    Marcus Smart
472    Marcus Smart
473    Marcus Smart
474    Marcus Smart
475    Marcus Smart
476    Marcus Smart
Name: a5, Length: 477, dtype: object
0      LeBron James
1      LeBron James
2      LeBron James
3      LeBron James
4      LeBron James
5      LeBron James
6      LeBron James
7      LeBron James
8      LeBron James
9      LeBron James
10     LeBron James
11     LeBron James
12     LeBron James
13     LeBron James
14     LeBron James
15     LeBron James
16     LeBron James
17     LeBron James
18     LeBron James
19     LeBron James
20     LeBron James
21     LeBron James
22     LeBron James
23     LeBron James
24     LeBron James
25     LeBron James
26     LeBron James
27     LeBron James
28     LeBron James
29     LeBron James
           ...
447    LeBron James
448    LeBron James
449    LeBron James
450    LeBron James
451    LeBron James
452    LeBron James
453    LeBron James
454    LeBron James
455    LeBron James
456    LeBron James
457    LeBron James
458    LeBron James
459    LeBron James
460    LeBron James
461    LeBron James
462    LeBron James
463    LeBron James
464    LeBron James
465    LeBron James
466    LeBron James
467    LeBron James
468    LeBron James
469    LeBron James
470    LeBron James
471    LeBron James
472    LeBron James
473    LeBron James
474    LeBron James
475    LeBron James
476    LeBron James
Name: h1, Length: 477, dtype: object
0      Jae Crowder
1      Jae Crowder
2      Jae Crowder
3      Jae Crowder
4      Jae Crowder
5      Jae Crowder
6      Jae Crowder
7      Jae Crowder
8      Jae Crowder
9      Jae Crowder
10     Jae Crowder
11     Jae Crowder
12     Jae Crowder
13     Jae Crowder
14     Jae Crowder
15     Jae Crowder
16     Jae Crowder
17     Jae Crowder
18     Jae Crowder
19     Jae Crowder
20     Jae Crowder
21     Jae Crowder
22     Jae Crowder
23     Jae Crowder
24     Jae Crowder
25     Jae Crowder
26     Jae Crowder
27     Jae Crowder
28     Jae Crowder
29     Jae Crowder
          ...
447    Dwyane Wade
448    Dwyane Wade
449    Dwyane Wade
450    Dwyane Wade
451    Dwyane Wade
452    Dwyane Wade
453    Dwyane Wade
454    Dwyane Wade
455    Dwyane Wade
456    Dwyane Wade
457    Dwyane Wade
458    Dwyane Wade
459    Dwyane Wade
460    Dwyane Wade
461    Dwyane Wade
462    Dwyane Wade
463    Dwyane Wade
464    Dwyane Wade
465    Jae Crowder
466    Jae Crowder
467    Jae Crowder
468    Jae Crowder
469    Jae Crowder
470    Jae Crowder
471    Jae Crowder
472    Jae Crowder
473    Jae Crowder
474    Jae Crowder
475    Jae Crowder
476    Jae Crowder
Name: h2, Length: 477, dtype: object
0        Kevin Love
1        Kevin Love
2        Kevin Love
3        Kevin Love
4        Kevin Love
5        Kevin Love
6        Kevin Love
7        Kevin Love
8        Kevin Love
9        Kevin Love
10       Kevin Love
11       Kevin Love
12       Kevin Love
13       Kevin Love
14       Kevin Love
15       Kevin Love
16       Kevin Love
17       Kevin Love
18       Kevin Love
19       Kevin Love
20       Kevin Love
21       Kevin Love
22       Kevin Love
23       Kevin Love
24       Kevin Love
25       Kevin Love
26       Kevin Love
27       Kevin Love
28       Kevin Love
29       Kevin Love
           ...
447      Kevin Love
448      Kevin Love
449      Kevin Love
450      Kevin Love
451      Kevin Love
452      Kevin Love
453      Kevin Love
454      Kevin Love
455      Kevin Love
456      Kevin Love
457      Kevin Love
458      Kevin Love
459      Kevin Love
460      Kevin Love
461      Kevin Love
462      Kevin Love
463      Kevin Love
464     Jae Crowder
465    Derrick Rose
466    Derrick Rose
467    Derrick Rose
468    Derrick Rose
469    Derrick Rose
470    Derrick Rose
471    Derrick Rose
472    Derrick Rose
473    Derrick Rose
474    Derrick Rose
475    Derrick Rose
476    Derrick Rose
Name: h3, Length: 477, dtype: object
0        Dwyane Wade
1        Dwyane Wade
2        Dwyane Wade
3        Dwyane Wade
4        Dwyane Wade
5        Dwyane Wade
6        Dwyane Wade
7        Dwyane Wade
8        Dwyane Wade
9        Dwyane Wade
10       Dwyane Wade
11       Dwyane Wade
12       Dwyane Wade
13       Dwyane Wade
14       Dwyane Wade
15       Dwyane Wade
16       Dwyane Wade
17       Dwyane Wade
18       Dwyane Wade
19       Dwyane Wade
20       Dwyane Wade
21       Dwyane Wade
22       Dwyane Wade
23       Dwyane Wade
24       Dwyane Wade
25       Dwyane Wade
26       Dwyane Wade
27       Dwyane Wade
28       Dwyane Wade
29       Dwyane Wade
           ...
447      Jae Crowder
448      Jae Crowder
449      Jae Crowder
450      Jae Crowder
451      Jae Crowder
452      Jae Crowder
453      Jae Crowder
454      Jae Crowder
455      Jae Crowder
456      Jae Crowder
457      Jae Crowder
458      Jae Crowder
459      Jae Crowder
460      Jae Crowder
461      Jae Crowder
462      Jae Crowder
463      Jae Crowder
464     Derrick Rose
465    Iman Shumpert
466    Iman Shumpert
467    Iman Shumpert
468    Iman Shumpert
469    Iman Shumpert
470    Iman Shumpert
471    Iman Shumpert
472    Iman Shumpert
473    Iman Shumpert
474    Iman Shumpert
475    Iman Shumpert
476    Iman Shumpert
Name: h4, Length: 477, dtype: object
0          Derrick Rose
1          Derrick Rose
2          Derrick Rose
3          Derrick Rose
4          Derrick Rose
5          Derrick Rose
6          Derrick Rose
7          Derrick Rose
8          Derrick Rose
9          Derrick Rose
10         Derrick Rose
11         Derrick Rose
12         Derrick Rose
13         Derrick Rose
14         Derrick Rose
15         Derrick Rose
16         Derrick Rose
17         Derrick Rose
18         Derrick Rose
19         Derrick Rose
20         Derrick Rose
21         Derrick Rose
22         Derrick Rose
23         Derrick Rose
24         Derrick Rose
25         Derrick Rose
26         Derrick Rose
27         Derrick Rose
28         Derrick Rose
29         Derrick Rose
             ...
447        Derrick Rose
448        Derrick Rose
449        Derrick Rose
450        Derrick Rose
451        Derrick Rose
452        Derrick Rose
453        Derrick Rose
454        Derrick Rose
455        Derrick Rose
456        Derrick Rose
457        Derrick Rose
458        Derrick Rose
459        Derrick Rose
460        Derrick Rose
461        Derrick Rose
462        Derrick Rose
463        Derrick Rose
464       Iman Shumpert
465    Tristan Thompson
466    Tristan Thompson
467    Tristan Thompson
468    Tristan Thompson
469    Tristan Thompson
470    Tristan Thompson
471    Tristan Thompson
472    Tristan Thompson
473    Tristan Thompson
474    Tristan Thompson
475    Tristan Thompson
476    Tristan Thompson
Name: h5, Length: 477, dtype: object
0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
447    4
448    4
449    4
450    4
451    4
452    4
453    4
454    4
455    4
456    4
457    4
458    4
459    4
460    4
461    4
462    4
463    4
464    4
465    4
466    4
467    4
468    4
469    4
470    4
471    4
472    4
473    4
474    4
475    4
476    4
Name: period, Length: 477, dtype: int64
0       0
1       0
2       2
3       2
4       2
5       2
6       2
7       2
8       2
9       2
10      2
11      4
12      4
13      4
14      4
15      4
16      4
17      4
18      4
19      4
20      4
21      4
22      6
23      6
24      6
25      6
26      6
27      6
28      6
29      6
       ..
447    94
448    94
449    96
450    96
451    98
452    98
453    98
454    98
455    98
456    98
457    98
458    98
459    98
460    98
461    98
462    98
463    98
464    98
465    98
466    98
467    99
468    99
469    99
470    99
471    99
472    99
473    99
474    99
475    99
476    99
Name: away_score, Length: 477, dtype: int64
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       1
14       3
15       3
16       3
17       5
18       5
19       5
20       7
21       7
22       7
23       7
24       7
25       7
26       8
27       9
28       9
29       9
      ...
447     92
448     93
449     93
450     95
451     95
452     95
453     95
454     95
455     96
456     97
457     97
458     97
459     99
460     99
461     99
462    102
463    102
464    102
465    102
466    102
467    102
468    102
469    102
470    102
471    102
472    102
473    102
474    102
475    102
476    102
Name: home_score, Length: 477, dtype: int64
0      00:12:00
1      00:12:00
2      00:11:44
3      00:11:27
4      00:11:23
5      00:11:21
6      00:11:18
7      00:11:02
8      00:10:59
9      00:10:51
10     00:10:51
11     00:10:48
12     00:10:32
13     00:10:32
14     00:10:21
15     00:10:05
16     00:09:56
17     00:09:49
18     00:09:33
19     00:09:31
20     00:09:29
21     00:09:22
22     00:09:14
23     00:08:52
24     00:08:49
25     00:08:49
26     00:08:49
27     00:08:49
28     00:08:34
29     00:08:33
         ...
447    00:02:58
448    00:02:58
449    00:02:41
450    00:02:24
451    00:02:03
452    00:01:43
453    00:01:43
454    00:01:43
455    00:01:43
456    00:01:43
457    00:01:31
458    00:01:27
459    00:01:19
460    00:01:04